// Generated by gencpp from file exercise_2/robotStateSrv.msg
// DO NOT EDIT!


#ifndef EXERCISE_2_MESSAGE_ROBOTSTATESRV_H
#define EXERCISE_2_MESSAGE_ROBOTSTATESRV_H

#include <ros/service_traits.h>


#include <exercise_2/robotStateSrvRequest.h>
#include <exercise_2/robotStateSrvResponse.h>


namespace exercise_2
{

struct robotStateSrv
{

typedef robotStateSrvRequest Request;
typedef robotStateSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robotStateSrv
} // namespace exercise_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exercise_2::robotStateSrv > {
  static const char* value()
  {
    return "9b8cd509dd6ad6e147547b5df51004bc";
  }

  static const char* value(const ::exercise_2::robotStateSrv&) { return value(); }
};

template<>
struct DataType< ::exercise_2::robotStateSrv > {
  static const char* value()
  {
    return "exercise_2/robotStateSrv";
  }

  static const char* value(const ::exercise_2::robotStateSrv&) { return value(); }
};


// service_traits::MD5Sum< ::exercise_2::robotStateSrvRequest> should match
// service_traits::MD5Sum< ::exercise_2::robotStateSrv >
template<>
struct MD5Sum< ::exercise_2::robotStateSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exercise_2::robotStateSrv >::value();
  }
  static const char* value(const ::exercise_2::robotStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise_2::robotStateSrvRequest> should match
// service_traits::DataType< ::exercise_2::robotStateSrv >
template<>
struct DataType< ::exercise_2::robotStateSrvRequest>
{
  static const char* value()
  {
    return DataType< ::exercise_2::robotStateSrv >::value();
  }
  static const char* value(const ::exercise_2::robotStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exercise_2::robotStateSrvResponse> should match
// service_traits::MD5Sum< ::exercise_2::robotStateSrv >
template<>
struct MD5Sum< ::exercise_2::robotStateSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exercise_2::robotStateSrv >::value();
  }
  static const char* value(const ::exercise_2::robotStateSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise_2::robotStateSrvResponse> should match
// service_traits::DataType< ::exercise_2::robotStateSrv >
template<>
struct DataType< ::exercise_2::robotStateSrvResponse>
{
  static const char* value()
  {
    return DataType< ::exercise_2::robotStateSrv >::value();
  }
  static const char* value(const ::exercise_2::robotStateSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXERCISE_2_MESSAGE_ROBOTSTATESRV_H
