// Generated by gencpp from file exercise_2/robotStateSrvRequest.msg
// DO NOT EDIT!


#ifndef EXERCISE_2_MESSAGE_ROBOTSTATESRVREQUEST_H
#define EXERCISE_2_MESSAGE_ROBOTSTATESRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace exercise_2
{
template <class ContainerAllocator>
struct robotStateSrvRequest_
{
  typedef robotStateSrvRequest_<ContainerAllocator> Type;

  robotStateSrvRequest_()
    : header()
    , id(0)  {
    }
  robotStateSrvRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::exercise_2::robotStateSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise_2::robotStateSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robotStateSrvRequest_

typedef ::exercise_2::robotStateSrvRequest_<std::allocator<void> > robotStateSrvRequest;

typedef boost::shared_ptr< ::exercise_2::robotStateSrvRequest > robotStateSrvRequestPtr;
typedef boost::shared_ptr< ::exercise_2::robotStateSrvRequest const> robotStateSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise_2::robotStateSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise_2::robotStateSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exercise_2::robotStateSrvRequest_<ContainerAllocator1> & lhs, const ::exercise_2::robotStateSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exercise_2::robotStateSrvRequest_<ContainerAllocator1> & lhs, const ::exercise_2::robotStateSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exercise_2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exercise_2::robotStateSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise_2::robotStateSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise_2::robotStateSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise_2::robotStateSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise_2::robotStateSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise_2::robotStateSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise_2::robotStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b48c956363ed6b741082033a5e95df37";
  }

  static const char* value(const ::exercise_2::robotStateSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb48c956363ed6b74ULL;
  static const uint64_t static_value2 = 0x1082033a5e95df37ULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise_2::robotStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise_2/robotStateSrvRequest";
  }

  static const char* value(const ::exercise_2::robotStateSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise_2::robotStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int32 id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::exercise_2::robotStateSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise_2::robotStateSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotStateSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise_2::robotStateSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercise_2::robotStateSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE_2_MESSAGE_ROBOTSTATESRVREQUEST_H
