// Generated by gencpp from file exercise_2/robotStateSrvResponse.msg
// DO NOT EDIT!


#ifndef EXERCISE_2_MESSAGE_ROBOTSTATESRVRESPONSE_H
#define EXERCISE_2_MESSAGE_ROBOTSTATESRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <exercise_1/robotMsg.h>

namespace exercise_2
{
template <class ContainerAllocator>
struct robotStateSrvResponse_
{
  typedef robotStateSrvResponse_<ContainerAllocator> Type;

  robotStateSrvResponse_()
    : header()
    , message()  {
    }
  robotStateSrvResponse_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::exercise_1::robotMsg_<ContainerAllocator>  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::exercise_2::robotStateSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise_2::robotStateSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robotStateSrvResponse_

typedef ::exercise_2::robotStateSrvResponse_<std::allocator<void> > robotStateSrvResponse;

typedef boost::shared_ptr< ::exercise_2::robotStateSrvResponse > robotStateSrvResponsePtr;
typedef boost::shared_ptr< ::exercise_2::robotStateSrvResponse const> robotStateSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise_2::robotStateSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise_2::robotStateSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exercise_2::robotStateSrvResponse_<ContainerAllocator1> & lhs, const ::exercise_2::robotStateSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exercise_2::robotStateSrvResponse_<ContainerAllocator1> & lhs, const ::exercise_2::robotStateSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exercise_2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exercise_2::robotStateSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise_2::robotStateSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise_2::robotStateSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise_2::robotStateSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise_2::robotStateSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise_2::robotStateSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise_2::robotStateSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81e8df687219db555fcc0a61760794c6";
  }

  static const char* value(const ::exercise_2::robotStateSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81e8df687219db55ULL;
  static const uint64_t static_value2 = 0x5fcc0a61760794c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise_2::robotStateSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise_2/robotStateSrvResponse";
  }

  static const char* value(const ::exercise_2::robotStateSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise_2::robotStateSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"exercise_1/robotMsg message\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: exercise_1/robotMsg\n"
"int32 roomId\n"
"string roomName\n"
"int32 batteryLevel\n"
;
  }

  static const char* value(const ::exercise_2::robotStateSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise_2::robotStateSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotStateSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise_2::robotStateSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercise_2::robotStateSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "message: ";
    s << std::endl;
    Printer< ::exercise_1::robotMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE_2_MESSAGE_ROBOTSTATESRVRESPONSE_H
