// Generated by gencpp from file intro_tutorial/srv1.msg
// DO NOT EDIT!


#ifndef INTRO_TUTORIAL_MESSAGE_SRV1_H
#define INTRO_TUTORIAL_MESSAGE_SRV1_H

#include <ros/service_traits.h>


#include <intro_tutorial/srv1Request.h>
#include <intro_tutorial/srv1Response.h>


namespace intro_tutorial
{

struct srv1
{

typedef srv1Request Request;
typedef srv1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv1
} // namespace intro_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::intro_tutorial::srv1 > {
  static const char* value()
  {
    return "2a5c7a37218262bae4fcfaa1007692aa";
  }

  static const char* value(const ::intro_tutorial::srv1&) { return value(); }
};

template<>
struct DataType< ::intro_tutorial::srv1 > {
  static const char* value()
  {
    return "intro_tutorial/srv1";
  }

  static const char* value(const ::intro_tutorial::srv1&) { return value(); }
};


// service_traits::MD5Sum< ::intro_tutorial::srv1Request> should match
// service_traits::MD5Sum< ::intro_tutorial::srv1 >
template<>
struct MD5Sum< ::intro_tutorial::srv1Request>
{
  static const char* value()
  {
    return MD5Sum< ::intro_tutorial::srv1 >::value();
  }
  static const char* value(const ::intro_tutorial::srv1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::intro_tutorial::srv1Request> should match
// service_traits::DataType< ::intro_tutorial::srv1 >
template<>
struct DataType< ::intro_tutorial::srv1Request>
{
  static const char* value()
  {
    return DataType< ::intro_tutorial::srv1 >::value();
  }
  static const char* value(const ::intro_tutorial::srv1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::intro_tutorial::srv1Response> should match
// service_traits::MD5Sum< ::intro_tutorial::srv1 >
template<>
struct MD5Sum< ::intro_tutorial::srv1Response>
{
  static const char* value()
  {
    return MD5Sum< ::intro_tutorial::srv1 >::value();
  }
  static const char* value(const ::intro_tutorial::srv1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::intro_tutorial::srv1Response> should match
// service_traits::DataType< ::intro_tutorial::srv1 >
template<>
struct DataType< ::intro_tutorial::srv1Response>
{
  static const char* value()
  {
    return DataType< ::intro_tutorial::srv1 >::value();
  }
  static const char* value(const ::intro_tutorial::srv1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTRO_TUTORIAL_MESSAGE_SRV1_H
